#!/usr/bin/env python3
"""Regenerate images/diagrams/qr-site.tex from a URL.

    python3 tools/make_qr.py            # uses site_url from edition.conf
    python3 tools/make_qr.py https://other.example

The QR on the back cover is drawn as vector rather than embedded as an image,
so it stays sharp at any size and can be reissued when the address changes.
Requires the `qrcode` package (pip install qrcode).
"""
import sys
from pathlib import Path
import qrcode

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "images" / "diagrams" / "qr-site.tex"


def site_url():
    """Default to site_url in edition.conf, so there is one address, not two."""
    for line in (ROOT / "edition.conf").read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line.startswith("site_url"):
            return line.partition("=")[2].strip().rstrip("/")
    raise SystemExit("edition.conf: no site_url")


def main(url):
    q = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_H, border=0)
    q.add_data(url)
    q.make(fit=True)
    m = q.get_matrix()
    n = len(m)
    out = [f"% QR code for {url} -- generated by tools/make_qr.py, do not hand-edit.",
           f"% {n}x{n} modules, error correction level H. Drawn as vector, so it is",
           "% sharp at any size. Regenerate if the URL changes.",
           "\\begin{tikzpicture}[x=1mm,y=1mm]",
           f"  \\fill[white] (-2,-2) rectangle ({n}+2,{n}+2);",
           "  \\begin{scope}[yscale=-1,yshift=%dmm]" % (-n)]
    for r, row in enumerate(m):
        c = 0
        while c < n:
            if row[c]:
                s = c
                while c < n and row[c]:
                    c += 1
                out.append(f"  \\fill[black] ({s},{r}) rectangle ({c},{r + 1});")
            else:
                c += 1
    out += ["  \\end{scope}", "\\end{tikzpicture}"]
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({n}x{n} modules) for {url}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else site_url())
